sudo: required

language: python
python: 2.7

services:
  - docker

env:
  - TOX_ENV=py27

git:
  submodules: false

before_install:
  - wget https://raw.githubusercontent.com/bgruening/galaxy-flavor-testing/master/Makefile
  - make docker_install
  - sudo apt-get install --no-install-recommends -y libgl1-mesa-dev libgl1-mesa-dri libglu1-mesa x11-xserver-utils x11vnc xinit xserver-xorg-video-dummy xserver-xorg-input-void
  - travis_wait 45 make docker_build
  - make docker_run
  - sleep 30

install:
  - make install

script:
  - make test_api
  - make test_ftp
  - make test_bioblend
  #- make test_docker_in_docker
